baseURL = 'https://shxlpa.vercel.app/'
languageCode = 'en-us'
title = 'SHILPA'
theme = 'hugo-coder'
enableEmoji = true

[params]
author = " "
info = ""
description = "Shilpa's personal website"
colorScheme = "light"  # We'll override CSS anyway

[[menu.main]]
name = "Design"
url = "/design/"
weight = 2

[[menu.main]]
name = "EE Cliffnotes"
url = "/eecliffnotes/"
weight = 3

[[menu.main]]
name = "Engineering"
url = "/engineering/"
weight = 1


[[menu.main]]
name = "Writing"
url = "/writing/"
weight = 3

